language: python
python: "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - gem install bundler
  - make install
script:
  - make book
  - make build
before_deploy:
  - git config --global user.email salva@unoyunodiez.com
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|stable)$
