name: base
channels:
- conda-forge
dependencies:
- python==3.7
- pip==19.*
- cython
- numpy
- matplotlib
- torchvision
- tabulate
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - qiskit
  - seaborn
  - -e ./qiskit-textbook-src
