name: Checks

on:
  # run when action is manually triggered
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Checks'
        required: false
        default: 'false'
  # run when a pull request is made
  pull_request:
  # run on pushes to master or stable branch
  push:
    branches: [ master, stable ]

jobs:
  # job id/key
  Checks:
    # job name
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          sudo apt-get -y install hunspell-en-us pandoc
          python -m pip install --upgrade pip setuptools wheel
          pip install scipy
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pyenchant

      - run: make check
        if: ${{ !cancelled() }}
        shell: bash
